Line """

Line Django settings for valeria_crowdbotics_5 project.

Line 

Line Generated by 'django-admin startproject' using Django 1.11.5.

Line 

Line For more information on this file, see

Line https://docs.djangoproject.com/en/1.11/topics/settings/

Line 

Line For the full list of settings and their values, see

Line https://docs.djangoproject.com/en/1.11/ref/settings/

Line """

Line 

Line import os

Line 

Line # Build paths inside the project like this: os.path.join(BASE_DIR, ...)

Line BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

Line 

Line 

Line # Quick-start development settings - unsuitable for production

Line # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

Line 

Line # SECURITY WARNING: keep the secret key used in production secret!

Line SECRET_KEY = '((1q0=er!jzniwq*@6**@=0h2%dz(an#cb=+kbd_8jmyltcl^o'

Line 

Line # SECURITY WARNING: don't run with debug turned on in production!

Line DEBUG = True

Line 

Line ALLOWED_HOSTS = []

Line 

Line 

Line # Application definition

Line 

Line INSTALLED_APPS = [

Line     'django.contrib.admin',

Line     'django.contrib.auth',

Line     'django.contrib.contenttypes',

Line     'django.contrib.sessions',

Line     'django.contrib.messages',

Line     'django.contrib.staticfiles',

Line ]

Line 

Line MIDDLEWARE = [

Line     'django.middleware.security.SecurityMiddleware',

Line     'django.contrib.sessions.middleware.SessionMiddleware',

Line     'django.middleware.common.CommonMiddleware',

Line     'django.middleware.csrf.CsrfViewMiddleware',

Line     'django.contrib.auth.middleware.AuthenticationMiddleware',

Line     'django.contrib.messages.middleware.MessageMiddleware',

Line     'django.middleware.clickjacking.XFrameOptionsMiddleware',

Line ]

Line 

Line ROOT_URLCONF = 'valeria_crowdbotics_5.urls'

Line 

Line TEMPLATES = [

Line     {

Line         'BACKEND': 'django.template.backends.django.DjangoTemplates',

Line         'DIRS': [],

Line         'APP_DIRS': True,

Line         'OPTIONS': {

Line             'context_processors': [

Line                 'django.template.context_processors.debug',

Line                 'django.template.context_processors.request',

Line                 'django.contrib.auth.context_processors.auth',

Line                 'django.contrib.messages.context_processors.messages',

Line             ],

Line         },

Line     },

Line ]

Line 

Line WSGI_APPLICATION = 'valeria_crowdbotics_5.wsgi.application'

Line 

Line 

Line # Database

Line # https://docs.djangoproject.com/en/1.11/ref/settings/#databases

Line 

Line DATABASES = {

Line     'default': {

Line         'ENGINE': 'django.db.backends.sqlite3',

Line         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

Line     }

Line }

Line 

Line 

Line # Password validation

Line # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

Line 

Line AUTH_PASSWORD_VALIDATORS = [

Line     {

Line         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

Line     },

Line     {

Line         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

Line     },

Line     {

Line         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

Line     },

Line     {

Line         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

Line     },

Line ]

Line 

Line 

Line # Internationalization

Line # https://docs.djangoproject.com/en/1.11/topics/i18n/

Line 

Line LANGUAGE_CODE = 'en-us'

Line 

Line TIME_ZONE = 'UTC'

Line 

Line USE_I18N = True

Line 

Line USE_L10N = True

Line 

Line USE_TZ = True

Line 

Line 

Line # Static files (CSS, JavaScript, Images)

Line # https://docs.djangoproject.com/en/1.11/howto/static-files/

Line 

Line STATIC_URL = '/static/'

Line 

Line import environ

Line env = environ.Env()

Line ALLOWED_HOSTS = ['*']

Line MIDDLEWARE += ['whitenoise.middleware.WhiteNoiseMiddleware']

Line 

Line DATABASES = {

Line     'default': env.db()

Line }

Line 

Line STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

Line STATICFILES_DIRS = [

Line     os.path.join(BASE_DIR, 'static')

Line ]

Line STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

